version: '3.8'
services:
  # appはコマンドでstartさせる
  # dbをmigrationかける
  # dbにseedを入れる
  # watchでstartする
  app:
    build:
      context: $PWD
      dockerfile: $PWD/docker/Dockerfile.local
    # For M1 only. other environments comment out.
    platform: linux/amd64
    ports:
      - "3100:3100"
    volumes:
      - .:/app:cached
    env_file: $PWD/env/local/.env
    depends_on:
      # @see https://gotohayato.com/content/533/
      db:
        condition: service_healthy
      aws:
        condition: service_healthy
    command: ["bash", "-c", "./bin/runner"]
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "test"
      # これなかったら気になる。
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - db-data:/var/lib/postgresql/data
    # 指定しておくとコンテナ停止時にサービスが再起動してくれる。
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  aws:
    platform: linux/amd64
    image: localstack/localstack:0.14.4
    ports:
      - "24566:4566" # すべてのサービスポート
    volumes:
      # データのマウント
      - 'localstack-data:/tmp/localstack'
    environment:
      # 有効にするサービス
      LOCALSTACK_SERVICES: dynamodb,s3,ses,sqs
      DEFAULT_REGION: ap-northeast-1
      USE_LIGHT_IMAGE: 1
      SKIP_INFRA_DOWNLOADS: 1
      START_WEB: 0
    healthcheck:
      # init スクリプトが完了する前に app が起動しないよう ヘルスチェックする（自分だからportは4566）
      test: ["CMD-SHELL", "curl http://localhost:4566/health | grep '\"initScripts\": \"initialized\"'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # TODO 以下の記入について調べる（おそらく作成するだけでいい場合の最低構文）
  db-data: {}
  localstack-data: {}
