version: '3.8'
services:

  # postgres:
  #   image: "postgres:14.5"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: "test"
  #     POSTGRES_PASSWORD: "test"
  #     POSTGRES_DB: "test"
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "test"
    volumes:
      - db-data:/var/lib/postgresql/data
    # 指定しておくとコンテナ停止時にサービスが再起動してくれる。
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # TODO 以下の記入について調べる（おそらく作成するだけでいい場合の最低構文）
  db-data: {}
