###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:16.17.0-slim
ENV NODE_ENV development

WORKDIR /app

COPY package.json yarn.lock ./
# --frozen-lockfileフラグを付けるとyarn.lockが更新されず、パッケージの更新が必要な場合は失敗するようになるのでこちらも付けておきます
RUN yarn install --frozen-lockfile

COPY . .
CMD "yarn" "start"


